services:
  # Rails のコンテナ
  backend:
    build:
      context: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e production -p ${PORT:-3000} -b '0.0.0.0'"
    buildCommand: "./bin/render-build.sh" # ←ここで自動マイグレーションも実行

    volumes:
      - ./backend:/rails:cached
    ports:
      - "3000:3000"
    env_file:  # ← .env を読み込む
      - backend/.env.production
      - backend/.env.development
    environment:
      RAILS_ENV: production
    depends_on:
      - db
    tty: true
    stdin_open: true


  # PostgreSQL のコンテナ
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Next.js のコンテナ
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
        - ./frontend:/next-app:cached
        - /next-app/node_modules
        - /next-app/.next
    ports:
      - "8000:3000"  # Next.js のデフォルトポート 3000 をホストの 8000 とマッピング
    depends_on:
      - backend  # 追加
    tty: true
    stdin_open: true

volumes:
  postgres_data: